@echo off

echo Upgrading pip...
python -m pip install --upgrade pip

echo Installing Scapy...
python -m pip install scapy

echo Installing NLTK...
python -m pip install nltk

echo Installing PyWifi...
python -m pip install pywifi

echo Installing Psutil...
python -m pip install psutil

echo Installing OpenAI...
python -m pip install openai

echo Installing Black...
python -m pip install black

echo Installing Pylite...
python -m pip install pylite

echo Installing Wifi...
python -m pip install wifi

echo Installing Requests...
python -m pip install requests

echo Installing other NLTK libraries...
python -m pip install nltk[all]

echo Installing Zxcvbn...
python -m pip install zxcvbn

echo Installing BeautifulSoup4...
python -m pip install beautifulsoup4

echo Installing urllib...
python -m pip install urllib

echo Installing Chatterbot...
python -m pip install chatterbot

echo Installing Numpy...
python -m pip install numpy

echo Installing Cryptography...
python -m pip install cryptography

echo Installing GPUtil...
python -m pip install gputil

echo Installing pyttsx3...
python -m pip install pyttsx3

echo Installing WMI...
python -m pip install wmi

echo Installing Transformers...
python -m pip install transformers

echo Installing qiskit...
python -m pip install qiskit
